controllers:
    resource: ../src/Controller/
    type: attribute


api_v1:
    resource: ./routes/api/v1/api_routes.yml
    prefix: /api/v1

home:
    methods: [ GET ]
    path: /
    defaults: { auth: false }
    controller: App\Controller\LobbyWars\HomeController::index